import { HeroicCultureType } from "../heroicCultures";

export const HeroicCultureHobbitsOfTheShire: HeroicCultureType = {
    name: 'Hobbits of the Shire',
    source: {
        pageReference: {
            textId: 'core-rulebook',
            pageNumber: 38,
        },
    },
    characteristics: {
        source: {
            pageReference: {
                textId: 'core-rulebook',
                pageNumber: 38,
            },
        },
        culturalBlessing: 'hobbitSense',
        standardOfLiving: 'common',
        culturalHandicap: 'halflings',
    },
    attributes: {
        source: {
            pageReference: {
                textId: 'core-rulebook',
                pageNumber: 38,
            },
        },
        table: [
            { roll: 1, strength: 3, heart: 6, wits: 5 },
            { roll: 2, strength: 3, heart: 7, wits: 4 },
            { roll: 3, strength: 2, heart: 7, wits: 5 },
            { roll: 4, strength: 4, heart: 6, wits: 4 },
            { roll: 5, strength: 4, heart: 5, wits: 5 },
            { roll: 6, strength: 2, heart: 6, wits: 6 },
        ],
    },
    derivedStats: {
        source: {
            pageReference: {
                textId: 'core-rulebook',
                pageNumber: 38,
            },
        },
        table: [
            { stat: 'endurance', attribute: 'strength', add: 18 },
            { stat: 'hope', attribute: 'heart', add: 10 },
            { stat: 'parry', attribute: 'wits', add: 12 },
        ],
    },
    skills: {
        source: {
            pageReference: {
                textId: 'core-rulebook',
                pageNumber: 38,
            },
        },
        table: [
            { skill: 'awe', rank: 0 },
            { skill: 'athletics', rank: 0 },
            { skill: 'awareness', rank: 2 },
            { skill: 'hunting', rank: 0 },
            { skill: 'song', rank: 2 },
            { skill: 'craft', rank: 1 },
            { skill: 'enhearten', rank: 0 },
            { skill: 'travel', rank: 0 },
            { skill: 'insight', rank: 2 },
            { skill: 'healing', rank: 1 },
            { skill: 'courtesy', rank: 2, underlined: true },
            { skill: 'battle', rank: 0 },
            { skill: 'persuade', rank: 2 },
            { skill: 'stealth', rank: 3, underlined: true },
            { skill: 'scan', rank: 0 },
            { skill: 'explore', rank: 0 },
            { skill: 'riddle', rank: 3 },
            { skill: 'lore', rank: 0 },
        ]
    },
    combatProficiencies: {
        source: {
            pageReference: {
                textId: 'core-rulebook',
                pageNumber: 39,
            },
        },
        table: [
            { proficiencyChoices: ['bows', 'swords'], rank: 2 },
            { proficiencyChoices: ['axes', 'bows', 'spears', 'swords'], rank: 1 },
        ],
    },
    distinctiveFeatures: {
        source: {
            pageReference: {
                textId: 'core-rulebook',
                pageNumber: 39,
            },
        },
        features: ['eager', 'fairSpoken', 'faithful', 'honourable', 'inquisitive', 'keenEyed', 'merry', 'rustic'],
        choose: 2,
    },
    languagesAndTypicalNames: {
        source: {
            pageReference: {
                textId: 'core-rulebook',
                pageNumber: 39,
            },
        },
        languages: ['common'],
        typicalNames: [
            { name: 'Andwise', type: 'male' },
            { name: 'Berilac', type: 'male' },
            { name: 'Bungo', type: 'male' },
            { name: 'Cottar', type: 'male' },
            { name: 'Doderic', type: 'male' },
            { name: 'Dudo', type: 'male' },
            { name: 'Erling', type: 'male' },
            { name: 'Fastred', type: 'male' },
            { name: 'Ferumbras', type: 'male' },
            { name: 'Folco', type: 'male' },
            { name: 'Gorhendad', type: 'male' },
            { name: 'Griffo', type: 'male' },
            { name: 'Halfred', type: 'male' },
            { name: 'Hamson', type: 'male' },
            { name: 'Ilberic', type: 'male' },
            { name: 'Isembold', type: 'male' },
            { name: 'Isengar', type: 'male' },
            { name: 'Longo', type: 'male' },
            { name: 'Marmadas', type: 'male' },
            { name: 'Marroc', type: 'male' },
            { name: 'Mungo', type: 'male' },
            { name: 'Odo', type: 'male' },
            { name: 'Orgulas', type: 'male' },
            { name: 'Otho', type: 'male' },
            { name: 'Posco', type: 'male' },
            { name: 'Reginard', type: 'male' },
            { name: 'Robin', type: 'male' },
            { name: 'Rudigar', type: 'male' },
            { name: 'Sadoc', type: 'male' },
            { name: 'Saradas', type: 'male' },
            { name: 'Tobold', type: 'male' },
            { name: 'Tolman', type: 'male' },
            { name: 'Adaldrida', type: 'female' },
            { name: 'Amaranth', type: 'female' },
            { name: 'Asphodel', type: 'female' },
            { name: 'Belba', type: 'female' },
            { name: 'Bell', type: 'female' },
            { name: 'Berylla', type: 'female' },
            { name: 'Camellia', type: 'female' },
            { name: 'Daisy', type: 'female' },
            { name: 'Eglantine', type: 'female' },
            { name: 'Estella', type: 'female' },
            { name: 'Gilly', type: 'female' },
            { name: 'Hanna', type: 'female' },
            { name: 'Lily', type: 'female' },
            { name: 'Malva', type: 'female' },
            { name: 'Marigold', type: 'female' },
            { name: 'May', type: 'female' },
            { name: 'Melilot', type: 'female' },
            { name: 'Menegilda', type: 'female' },
            { name: 'Mentha', type: 'female' },
            { name: 'Mirabella', type: 'female' },
            { name: 'Myrtle', type: 'female' },
            { name: 'Pearl', type: 'female' },
            { name: 'Peony', type: 'female' },
            { name: 'Pervinca', type: 'female' },
            { name: 'Pimpernel', type: 'female' },
            { name: 'Primrose', type: 'female' },
            { name: 'Primula', type: 'female' },
            { name: 'Prisca', type: 'female' },
            { name: 'Rosamunda', type: 'female' },
            { name: 'Ruby', type: 'female' },
            { name: 'Salvia', type: 'female' },
            { name: 'Baggins', type: 'family' },
            { name: 'Boffin', type: 'family' },
            { name: 'Bolger', type: 'family' },
            { name: 'Bracegirdle', type: 'family' },
            { name: 'Brandybuck', type: 'family' },
            { name: 'Brown', type: 'family' },
            { name: 'Brownlock', type: 'family' },
            { name: 'Bunce', type: 'family' },
            { name: 'Burrows', type: 'family' },
            { name: 'Cotton', type: 'family' },
            { name: 'Gamgee', type: 'family' },
            { name: 'Gardner', type: 'family' },
            { name: 'Goldworthy', type: 'family' },
            { name: 'Goodbody', type: 'family' },
            { name: 'Goodchild', type: 'family' },
            { name: 'Grubb', type: 'family' },
            { name: 'Headstrong', type: 'family' },
            { name: 'Hornblower', type: 'family' },
            { name: 'Maggot', type: 'family' },
            { name: 'Noakes', type: 'family' },
            { name: 'North-tooks', type: 'family' },
            { name: 'Proudfoot', type: 'family' },
            { name: 'Puddifoot', type: 'family' },
            { name: 'Roper', type: 'family' },
            { name: 'Rumble', type: 'family' },
            { name: 'Sackville', type: 'family' },
            { name: 'Smallburrow', type: 'family' },
            { name: 'Took', type: 'family' },
            { name: 'Twofoot', type: 'family' },
            { name: 'Whitfoot', type: 'family' },
        ]
    }
}