import { HeroicCultureType } from "../heroicCultures";

export const HeroicCultureBeornings: HeroicCultureType = {
    name: 'Beornings',
    source: {
        pageReference: {
            textId: 'peoples-of-wilderland',
            pageNumber: 2,
        },
    },
    characteristics: {
        source: {
            pageReference: {
                textId: 'peoples-of-wilderland',
                pageNumber: 2,
            },
        },
        culturalBlessing: 'furious',
        standardOfLiving: 'common',
    },
    attributes: {
        source: {
            pageReference: {
                textId: 'peoples-of-wilderland',
                pageNumber: 3,
            },
        },
        table: [
            { roll: 1, strength: 5, heart: 7, wits: 2 },
            { roll: 2, strength: 4, heart: 7, wits: 3 },
            { roll: 3, strength: 5, heart: 6, wits: 3 },
            { roll: 4, strength: 4, heart: 6, wits: 4 },
            { roll: 5, strength: 5, heart: 5, wits: 4 },
            { roll: 6, strength: 6, heart: 6, wits: 2 },
        ],
    },
    derivedStats: {
        source: {
            pageReference: {
                textId: 'peoples-of-wilderland',
                pageNumber: 3,
            },
        },
        table: [
            { stat: 'endurance', attribute: 'strength', add: 22 },
            { stat: 'hope', attribute: 'heart', add: 6 },
            { stat: 'parry', attribute: 'wits', add: 12 },
        ],
    },
    skills: {
        source: {
            pageReference: {
                textId: 'peoples-of-wilderland',
                pageNumber: 3,
            },
        },
        table: [
            { skill: 'awe', rank: 3 },
            { skill: 'athletics', rank: 2, underlined: true },
            { skill: 'awareness', rank: 2 },
            { skill: 'hunting', rank: 2 },
            { skill: 'song', rank: 0 },
            { skill: 'craft', rank: 1 },
            { skill: 'enhearten', rank: 1 },
            { skill: 'travel', rank: 1 },
            { skill: 'insight', rank: 3 },
            { skill: 'healing', rank: 1 },
            { skill: 'courtesy', rank: 0 },
            { skill: 'battle', rank: 1 },
            { skill: 'persuade', rank: 0 },
            { skill: 'stealth', rank: 1 },
            { skill: 'scan', rank: 1, underlined: true },
            { skill: 'explore', rank: 0 },
            { skill: 'riddle', rank: 1 },
            { skill: 'lore', rank: 0 },
        ]
    },
    combatProficiencies: {
        source: {
            pageReference: {
                textId: 'peoples-of-wilderland',
                pageNumber: 3,
            },
        },
        table: [
            { proficiencyChoices: ['axes', 'spears'], rank: 2 },
            { proficiencyChoices: ['axes', 'bows', 'spears', 'swords'], rank: 1 },
        ],
    },
    distinctiveFeatures: {
        source: {
            pageReference: {
                textId: 'peoples-of-wilderland',
                pageNumber: 3,
            },
        },
        features: ['bold', 'fierce', 'generous', 'honourable', 'rustic', 'stern', 'tall', 'wary'],
        choose: 2,
    },
    languagesAndTypicalNames: {
        source: {
            pageReference: {
                textId: 'peoples-of-wilderland',
                pageNumber: 3,
            },
        },
        languages: ['common', "regionalMannishValesOfTheAnduinRiver"],
        typicalNames: [
            { name: 'Agilfrid', type: 'male' },
            { name: 'Arnulf', type: 'male' },
            { name: 'Avagis', type: 'male' },
            { name: 'Baldac', type: 'male' },
            { name: 'Barald', type: 'male' },
            { name: 'Berangar', type: 'male' },
            { name: 'Cilderic', type: 'male' },
            { name: 'Eberulf', type: 'male' },
            { name: 'Eboric', type: 'male' },
            { name: 'Evermud', type: 'male' },
            { name: 'Frideger', type: 'male' },
            { name: 'Garivald', type: 'male' },
            { name: 'Geberic', type: 'male' },
            { name: 'Gerold', type: 'male' },
            { name: 'Grimfast', type: 'male' },
            { name: 'Hartmut', type: 'male' },
            { name: 'Hathus', type: 'male' },
            { name: 'Heriwulf', type: 'male' },
            { name: 'Ingund', type: 'male' },
            { name: 'Iwald', type: 'male' },
            { name: 'Leudast', type: 'male' },
            { name: 'Magneric', type: 'male' },
            { name: 'Maracar', type: 'male' },
            { name: 'Otbert', type: 'male' },
            { name: 'Ramnulf', type: 'male' },
            { name: 'Rathar', type: 'male' },
            { name: 'Rigunth', type: 'male' },
            { name: 'Sigeric', type: 'male' },
            { name: 'Theodard', type: 'male' },
            { name: 'Thorismund', type: 'male' },
            { name: 'Walcaud', type: 'male' },
            { name: 'Widuven', type: 'male' },
            { name: 'Wulferd', type: 'male' },
            { name: 'Adosinda', type: 'female' },
            { name: 'Amalfrida', type: 'female' },
            { name: 'Amalina', type: 'female' },
            { name: 'Avagisa', type: 'female' },
            { name: 'Avina', type: 'female' },
            { name: 'Basina', type: 'female' },
            { name: 'Beranhild', type: 'female' },
            { name: 'Brunihild', type: 'female' },
            { name: 'Deuteria', type: 'female' },
            { name: 'Gailavira', type: 'female' },
            { name: 'Garsendis', type: 'female' },
            { name: 'Geleswinta', type: 'female' },
            { name: 'Gelvira', type: 'female' },
            { name: 'Grimhild', type: 'female' },
            { name: 'Gunteuch', type: 'female' },
            { name: 'Hermesind', type: 'female' },
            { name: 'Heva', type: 'female' },
            { name: 'Hilduara', type: 'female' },
            { name: 'Ingund', type: 'female' },
            { name: 'Radegund', type: 'female' },
            { name: 'Sichild', type: 'female' },
            { name: 'Verich', type: 'female' },
            { name: 'Waldrada', type: 'female' },
            { name: 'Wisigard', type: 'female' },
            { name: 'from [a specific place]', type: 'byname', example: 'from the High Pass' },
            { name: 'of [a specific place]', type: 'byname', example: 'of the Mountains' },
            { name: 'the Bald', type: 'byname' },
            { name: 'the Black', type: 'byname' },
            { name: 'the Bold', type: 'byname' },
            { name: 'the Captain', type: 'byname' },
            { name: 'the Cloaked', type: 'byname' },
            { name: 'the Crooked', type: 'byname' },
            { name: 'the Eloquent', type: 'byname' },
            { name: 'the Foresighted', type: 'byname' },
            { name: 'the Good', type: 'byname' },
            { name: 'the Good-sword', type: 'byname' },
            { name: 'the Loyal', type: 'byname' },
            { name: 'the Old', type: 'byname' },
            { name: 'the Pugnacious', type: 'byname' },
            { name: 'the Quick-witted', type: 'byname' },
            { name: 'the Quiet', type: 'byname' },
            { name: 'the Red', type: 'byname' },
            { name: 'of the Red-shield', type: 'byname' },
            { name: 'the Rich', type: 'byname' },
            { name: 'the Runner', type: 'byname' },
            { name: 'the Sad', type: 'byname' },
            { name: 'the Sharp', type: 'byname' },
            { name: 'the Smith', type: 'byname' },
            { name: 'the Thin', type: 'byname' },
            { name: 'the Trouble-maker', type: 'byname' },
            { name: 'the Wise', type: 'byname' },
            { name: 'the Young', type: 'byname' },
        ]
    }
}